### ISSUE TITLE
Añadir badge npm to repo

### ISSUE THREAD

**Issue by crguezl** [GeneticsJS/GeneticsJS#3]
1. There are a few badges in the README.md that look wrong in the npm site https://www.npmjs.com/package/genetics-js
  
  <img width="790" alt="Captura de pantalla 2020-12-21 a las 9 16 36" src="https://user-images.githubusercontent.com/1142554/102760373-5286e300-436d-11eb-8350-eb5edd79fdb9.png">
1. Add npm badge to the list of badges

**Comment by crguezl** [comment]
See [shields.io](https://github.com/badges/shields)

**Comment by CristoNavarro** [comment]
@crguezl @esegredo Me había despistado despistado de este issue. Ya he añadido el badge del paquete en npm.

**Comment by esegredo** [comment]
Muchas gracias, Cristo. Cierro el issue.
