### ISSUE TITLE
:bug:

### ISSUE THREAD

**Issue by crguezl** [GeneticsJS/GeneticsJS#4]
> El otro día después de la reunión estuve intentando publicar la nueva versión de la librería (eliminando la carpeta lib), por lo que antes de publicarla hice un patch. Previamente todos los tests corrían perfectamente y después del patch me fijé que aparecieron los mismos errores que cuando publicamos el paquete. Entonces estuve investigando y vi que el commit hecho después del npm version patch había modificado el código devolviéndolo a la versión con un error. Volví a hacer un commit arreglándolo y de nuevo el patch por si acaso, y sucedió lo mismo.
Estuve investigando, pero no he logrado encontrar una solución, ya que lo único que debería hacer el commit del patch es modificar la versión en el package.json, y en los scripts de Cristian no vi tampoco nada extraño.
No sé si se les ocurre algún motivo para que suceda esto, o quizás no estoy viendo el error.

Observo que en el `package.json` Cristian tenia un preversion, postversion, etc. 
Mira la [doc de npm version](https://docs.npmjs.com/cli/v6/commands/npm-version).
Esto estaba dando lugar a push y cambios automáticos.

El caso es que debían funcionar.

Lo que he hecho es comentarlos en el  `package.json` con lo que inhibimos los push automaticos.
He hecho una publicación `1.0.4` y parece que corren las pruebas.

**Comment by CristoNavarro** [comment]
Yo había revisado dichos scripts, pero acabo de caer en que Prettier es el que está metiendo el error. He encontrado cómo ignorar esa línea para que no introduzca el error.

**Comment by CristoNavarro** [comment]
@crguezl He arreglado el problema con el Prettier y probé con los scripts a publicar un nuevo parche y funciona perfectamente.

**Comment by crguezl** [comment]
¡Estupendo 👍 !
