### ISSUE TITLE
documentacion :bug:

### ISSUE THREAD

**Issue by crguezl** [GeneticsJS/GeneticsJS#5]
A mi la documentación no se construye bien. 

El fichero tdconfig.json en la versión de Cristian ha desaparecido.

```
➜  cristo-navarro-geneticsjs git:(master) ✗ npm run docs

> genetics-js@1.0.4 docs /Users/casianorodriguezleon/campus-virtual/2021/tfg2021/TFG_2021_CristoDanielNavarro/cristo-navarro-geneticsjs
> typedoc --out docs/ --mode modules --tsconfig tdconfig.json


Using TypeScript 3.2.4 from /Users/casianorodriguezleon/campus-virtual/2021/tfg2021/TFG_2021_CristoDanielNavarro/cristo-navarro-geneticsjs/node_modules/typedoc/node_modules/typescript/lib
Error: /Users/casianorodriguezleon/campus-virtual/2021/tfg2021/TFG_2021_CristoDanielNavarro/cristo-navarro-geneticsjs/src/mutation/numeric/integer/RandomResetting.ts(12)
```

**Comment by CristoNavarro** [comment]
He revisado los commits posteriores a las versiones de Cristian y vi que en el commit _"Add index at every folder"_ (00575c4ee59e10be61bdc10302ae26ebb87fbff8), Zelante eliminó el fichero tdconfig.json.

**Comment by crguezl** [comment]
Ajá!.

 Habrá que conseguir que la documentación se genere.
El ejemplo del Knapsack me está dando errores cuando lo re-compilo.

**Comment by CristoNavarro** [comment]
Aún no he actualizado la mochila, tengo los cambios en local y funciona, pero no me dio tiempo de revisarlo bien y subirlo. Restauré el fichero de Cristian pero me sigue dando errores la documentación, aún estoy revisándolo.

**Comment by CristoNavarro** [comment]
Estuve probando y puede que el problema fuese la versión que se estaba usando de TypeDoc y TypeScript. Al poner una versión más moderna de ambos, parece que genera bien la documentación.

**Comment by crguezl** [comment]
👍 🚀  done!
